spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1993

spring.jpa.hibernate.ddl-auto=update

# Mostra no console o que o Java está fazendo no banco (ajuda a debugar)
spring.jpa.show-sql=true